<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Invio di Modulo Home',
	'heading' => 'Nuovo invio del modulo',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Selezionato',
		'checkbox_unchecked' => 'Non selezionato',
		'submitted_from' => 'Modulo inviato dal sito Web: %s',
		'submitted_by' => 'Indirizzo IP del visitatore: %s',
		'too_many_submissions' => 'Troppi invii recenti da questo IP',
		'failed_to_send_email' => 'Invio e-mail non riuscito',
		'invalid_reCAPTCHA_private_key' => 'Chiave privata reCAPTCHA non valida.',
		'invalid_reCAPTCHA2_private_key' => 'Chiave privata reCAPTCHA 2.0 non valida.',
		'invalid_reCAPTCHA2_server_response' => 'Risposta server reCAPTCHA 2.0 non valida.',
		'invalid_field_type' => 'Tipo di campo \"%s\" sconosciuto.',
		'invalid_form_config' => 'Il campo \"%s\" ha una configurazione non valida.',
		'unknown_method' => 'Metodo di richiesta server sconosciuto'
	),
	'email' => array(
		'from' => 'pietro.forino@mail.polimi.it',
		'to' => 'pietro.forino@mail.polimi.it'
	),
	'fields' => array(
		'custom_U2759' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nome',
			'required' => true,
			'errors' => array(
				'required' => 'Il campo \'Nome\' è obbligatorio.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'E-mail',
			'required' => true,
			'errors' => array(
				'required' => 'Il campo \'E-mail\' è obbligatorio.',
				'format' => 'L\'e-mail del campo \"E-mail\" non è valido.'
			)
		),
		'custom_U2763' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Messaggio',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
